github.com:
    users:
        amateur-hacker:
            oauth_token: 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
    git_protocol: ssh
    user: amateur-hacker
    oauth_token: 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
