[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "shift_monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
  "layout_center",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

# [scratchpads.music]
# animation = "fromTop"
# command = "kitty --class music -e ncspot"
# class = "music"
# size = "75% 60%"

[scratchpads.file]
animation = "fromTop"
command = "kitty --class fmcli -e lf ~/"
class = "fmcli"
size = "75% 60%"
position = "12% 20%"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm ~/"
class = "kitty-dropterm"
size = "75% 60%"
position = "12% 20%"

[scratchpads.volume]
animation = "fromTop"
command = "kitty --class audiocontrolcli -e pulsemixer"
class = "audiocontrolcli"
lazy = true
size = "75% 60%"
position = "12% 20%"
unfocus = "hide"

[layout_center]
margin = 60
offset = [0, 30]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"

# [monitors]
# unknown = "wlrlui"
#
[monitors.placement]
"eDP-1".rightOf = ["HDMI-A-1"]
